#!/usr/bin/env python3
# AI: below section was generated by an AI
"""
Batch analyze multiple images and generate a merged dynamic recipe collection.
Each image becomes one "scene segment" in the final playlist.

Usage:
    python3 analyze_multi_images.py <url1> <url2> [url3] [url4] [--scene "Scene Name"]
    python3 analyze_multi_images.py --urls-file urls.txt [--scene "Scene Name"]
    python3 analyze_multi_images.py <url1> <url2> --json --scene "Jasmine Blooms"

Output: JSON with {success, scene, recipes: [...], playlist_suggestion}
Each recipe has colors, fx, sx, ix, bri - ready for build_playlist.py
"""
import json
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, SCRIPT_DIR)

from analyze_image import load_image, analyze_colors, build_wled_palette, suggest_recipe, load_config


# SMOOTH effects only - verified non-flashing, gradient-based animation
# NEVER use flashing/strobe effects: Pacifica(77), Flow(75), Fire(35), Fireworks(33),
# Blink(1), Twinkle(17), Party(6), Rainbow Runner(11), Splash(19)
SMOOTH_FX_WARM = [13, 21, 39]           # Sunset, Sunset2, Autumn - smooth warm gradients
SMOOTH_FX_NATURE = [10, 12, 14, 18, 26] # Forest, Fade, Rivendell, Dissolve, Beech - smooth nature
SMOOTH_FX_COOL = [2, 12, 18, 50]        # Breathe, Fade, Dissolve, Aurora - smooth cool
SMOOTH_FX_PARTY = [12, 18, 20]          # Fade, Dissolve, Pastel - smooth gentle


def pick_dynamic_fx(theme, index):
    """Pick a smooth fx for the theme, rotating through the list to add variety."""
    if theme == "warm":
        pool = SMOOTH_FX_WARM
    elif theme == "nature":
        pool = SMOOTH_FX_NATURE
    elif theme == "cool":
        pool = SMOOTH_FX_COOL
    else:
        pool = SMOOTH_FX_PARTY
    return pool[index % len(pool)]


def analyze_one_image(image_source, config, index):
    """Analyze a single image and return a recipe dict."""
    color_cfg = config.get("color_analysis", {})
    img = load_image(image_source)
    colors = analyze_colors(
        img,
        num_colors=color_cfg.get("num_colors", 5),
        min_saturation=color_cfg.get("min_saturation", 30),
        min_brightness=color_cfg.get("min_brightness", 20),
        avoid_overdark=color_cfg.get("avoid_overdark", True)
    )
    suggestion = suggest_recipe(colors, config)
    theme = suggestion.get("theme", "nature")

    # Override fx with a dynamic one from the theme pool
    dynamic_fx = pick_dynamic_fx(theme, index)

    # Use SLOW speed for smooth, non-flashing effect
    # NEVER use SX > 128 - causes strobe
    sx = max(50, min(90, suggestion.get("sx", 70)))
    ix = max(80, min(120, suggestion.get("ix", 100)))

    recipe = {
        "name": f"Scene {index + 1}",
        "colors": [c["rgb"] for c in colors[:3]],
        "palette_data": build_wled_palette(colors),
        "fx": dynamic_fx,
        "sx": sx,
        "ix": ix,
        "bri": suggestion.get("bri", 200),
        "pal": 0,
        "theme": theme,
        "rationale": f"{suggestion.get('rationale', '')} | Dynamic FX {dynamic_fx} applied",
        "image_source": image_source,
        "color_details": [{"hex": c["hex"], "ratio": c["ratio"]} for c in colors]
    }
    return recipe


def merge_colors_from_recipes(recipes):
    """Merge colors from multiple recipes into 3 representative colors.
    Groups by hue range (warm/nature/cool/party) and picks top colors.
    This produces a single col array that captures the essence of all images.
    """
    all_colors = []
    for r in recipes:
        for c in r.get("color_details", []):
            all_colors.append(c)

    if not all_colors:
        return [[128, 128, 128], [128, 128, 128], [128, 128, 128]]

    # Sort by ratio descending
    all_colors.sort(key=lambda x: x.get("ratio", 0), reverse=True)

    # Pick top 3 distinct colors (avoid similar colors)
    from analyze_image import rgb_to_hsv
    picked = []
    for c in all_colors:
        rgb = c["rgb"] if "rgb" in c else [int(c["hex"][1:3], 16), int(c["hex"][3:5], 16), int(c["hex"][5:7], 16)]
        h, s, v = rgb_to_hsv(*rgb)
        # Check if this color is too similar to any already picked
        too_similar = False
        for p in picked:
            p_rgb = p["rgb"] if "rgb" in p else [int(p["hex"][1:3], 16), int(p["hex"][3:5], 16), int(p["hex"][5:7], 16)]
            p_h, _, _ = rgb_to_hsv(*p_rgb)
            if abs(h - p_h) < 30 and abs(rgb[0] - p_rgb[0]) < 50 and abs(rgb[1] - p_rgb[1]) < 50:
                too_similar = True
                break
        if not too_similar:
            picked.append(c)
        if len(picked) >= 3:
            break

    # Fill remaining slots with top colors if not enough distinct ones
    while len(picked) < 3 and all_colors:
        for c in all_colors:
            if c not in picked:
                picked.append(c)
                break

    merged = []
    for c in picked[:3]:
        if "rgb" in c:
            merged.append(c["rgb"])
        else:
            merged.append([int(c["hex"][1:3], 16), int(c["hex"][3:5], 16), int(c["hex"][5:7], 16)])

    while len(merged) < 3:
        merged.append(merged[0] if merged else [128, 128, 128])

    return merged


def pick_best_dynamic_fx(recipes):
    """Pick the single best smooth fx based on the dominant theme across recipes.
    ONLY use verified smooth, non-flashing effects.
    NEVER use: Pacifica(77), Flow(75), Fire(35), Fireworks(33), Blink(1), Twinkle(17), Party(6)
    These flash/strobe and are explicitly rejected by users.
    """
    theme_counts = {}
    for r in recipes:
        t = r.get("theme", "nature")
        theme_counts[t] = theme_counts.get(t, 0) + 1
    dominant_theme = max(theme_counts, key=theme_counts.get)

    # Use ONLY verified smooth, gradient-based effects
    # FX 12 (Fade): smooth color crossfade, no strobe
    # FX 18 (Dissolve): soft color melting, no strobe
    # FX 2 (Breathe): gentle breathing, no strobe
    # FX 10 (Forest): smooth nature gradient
    # FX 14 (Rivendell): cool forest, smooth
    # FX 13 (Sunset): warm gradient, smooth
    # FX 50 (Aurora): northern lights, smooth
    if dominant_theme == "warm":
        return 13  # Sunset - smooth warm gradient
    elif dominant_theme == "nature":
        return 12  # Fade - smoothest color crossfade
    elif dominant_theme == "cool":
        return 50  # Aurora - smooth northern lights
    else:
        return 12  # Fade - default smooth


def build_merged_recipe(recipes, scene_name):
    """Build a single merged recipe from multiple image recipes.
    Uses color merging + best dynamic fx for continuous animation.
    This is more reliable than playlist (which has bugs on some WLED dev builds).
    """
    merged_colors = merge_colors_from_recipes(recipes)
    fx = pick_best_dynamic_fx(recipes)

    # Build palette from ALL colors across all recipes
    all_palette_colors = []
    for r in recipes:
        for c in r.get("color_details", []):
            # Convert hex to rgb if needed
            if "rgb" not in c and "hex" in c:
                h = c["hex"].lstrip("#")
                c = {**c, "rgb": [int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)]}
            all_palette_colors.append(c)

    from analyze_image import build_wled_palette
    palette_data = build_wled_palette(all_palette_colors[:8])  # up to 8 colors for rich palette

    # Use SLOW speed and LOW intensity for smooth, non-flashing animation
    # SX 60-80: very slow, meditative (ref: effects_palettes.md)
    # IX 80-120: subtle, balanced (ref: effects_palettes.md)
    # NEVER use SX > 128 or IX > 150 - causes strobe/flashing
    sx = 70   # slow, gentle movement
    ix = 100  # subtle, balanced intensity
    bri = 180 # comfortable brightness

    themes = list(set(r.get("theme", "nature") for r in recipes))

    return {
        "name": scene_name,
        "colors": merged_colors,
        "palette_data": palette_data,
        "fx": fx,
        "sx": sx,
        "ix": ix,
        "bri": bri,
        "pal": 0,
        "theme": themes[0] if len(themes) == 1 else "mixed",
        "rationale": f"Merged {len(recipes)} images, dominant theme: {themes}, dynamic FX {fx} for continuous animation",
        "image_count": len(recipes),
        "themes_detected": themes,
        "merged_colors_hex": ["#{:02X}{:02X}{:02X}".format(c[0], c[1], c[2]) for c in merged_colors]
    }


def analyze_multi_images(image_sources, scene_name="Untitled Scene"):
    """Analyze multiple images and return a collection of recipes + merged recipe."""
    config = load_config()
    recipes = []
    errors = []

    for i, src in enumerate(image_sources):
        try:
            recipe = analyze_one_image(src, config, i)
            recipes.append(recipe)
        except Exception as e:
            errors.append({"image": src, "error": str(e)})

    if not recipes:
        return {"success": False, "message": "No images could be analyzed", "errors": errors}

    # Build merged recipe (single dynamic fx with merged colors)
    merged_recipe = build_merged_recipe(recipes, scene_name)

    # Build playlist suggestion (for WLED versions where playlist auto-advance works)
    total_duration_sec = 60
    per_scene_sec = max(5, total_duration_sec // len(recipes))
    playlist_suggestion = {
        "total_duration_sec": total_duration_sec,
        "per_scene_sec": per_scene_sec,
        "scene_count": len(recipes),
        "repeat": 0,  # 0 = infinite loop
        "transition_ms": 500,
        "themes_detected": list(set(r["theme"] for r in recipes))
    }

    return {
        "success": True,
        "scene": scene_name,
        "recipes": recipes,
        "merged_recipe": merged_recipe,
        "playlist_suggestion": playlist_suggestion,
        "errors": errors,
        "message": f"Analyzed {len(recipes)} images for scene '{scene_name}', merged into 1 dynamic recipe (FX {merged_recipe['fx']})"
    }


def main():
    if "--help" in sys.argv or "-h" in sys.argv or len(sys.argv) < 2:
        print(__doc__)
        sys.exit(0)

    scene_name = "Untitled Scene"
    json_only = False
    urls_file = None
    image_sources = []

    i = 1
    while i < len(sys.argv):
        arg = sys.argv[i]
        if arg == "--scene" and i + 1 < len(sys.argv):
            scene_name = sys.argv[i + 1]; i += 2
        elif arg == "--json":
            json_only = True; i += 1
        elif arg == "--urls-file" and i + 1 < len(sys.argv):
            urls_file = sys.argv[i + 1]; i += 2
        else:
            image_sources.append(arg); i += 1

    if urls_file:
        with open(urls_file, "r") as f:
            image_sources = [line.strip() for line in f if line.strip() and not line.startswith("#")]

    if not image_sources:
        print(json.dumps({"success": False, "message": "No image URLs provided"}, ensure_ascii=False))
        sys.exit(1)

    # Limit to 6 images max
    if len(image_sources) > 6:
        image_sources = image_sources[:6]

    result = analyze_multi_images(image_sources, scene_name)

    if not json_only and result.get("success"):
        print(f"Scene: {scene_name}")
        print(f"Images analyzed: {len(result['recipes'])}")
        for i, r in enumerate(result['recipes']):
            print(f"\n  Recipe {i+1}: FX={r['fx']} SX={r['sx']} IX={r['ix']} Theme={r['theme']}")
            print(f"    Colors: {', '.join(c['hex'] for c in r['color_details'])}")
        merged = result.get('merged_recipe', {})
        print(f"\n  === Merged Recipe (RECOMMENDED) ===")
        print(f"  FX={merged.get('fx')} SX={merged.get('sx')} IX={merged.get('ix')} Bri={merged.get('bri')}")
        print(f"  Merged Colors: {', '.join(merged.get('merged_colors_hex', []))}")
        print(f"  Theme: {merged.get('theme')}")
        print(f"  Rationale: {merged.get('rationale')}")
        print(f"\n  Use: python3 scripts/apply_recipe.py with merged_recipe JSON")
        print("\n--- JSON ---")

    print(json.dumps(result, indent=2, ensure_ascii=False))
    sys.exit(0 if result.get("success") else 1)


if __name__ == "__main__":
    main()
# AI: end
