#!/usr/bin/env python3
# AI: below section was generated by an AI
"""
Image color analyzer for WLED light recipe.
Extracts dominant colors from an image using color quantization,
filters out over-dark/over-bright colors, and outputs a palette
suitable for WLED LED strips.

Optimized for speed: uses PIL quantize() for fast color reduction,
falls back to histogram-based method if numpy/sklearn unavailable.

Usage:
    python3 analyze_image.py <image_url_or_path>
    python3 analyze_image.py <image_url_or_path> --num-colors 5
    python3 analyze_image.py <image_url_or_path> --json          # output JSON only

Output: JSON with {success, colors, palette_data, recipe_suggestion}
"""
import json
import os
import sys
import urllib.request
import io

CONFIG_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "config.json")


def load_config():
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def load_image(source, max_size=150):
    """Load image from URL, file path, or base64. Returns PIL Image."""
    try:
        from PIL import Image
    except ImportError:
        raise RuntimeError("PIL/Pillow is required. Install with: pip install Pillow")

    if source.startswith(("http://", "https://")):
        req = urllib.request.Request(source, headers={"User-Agent": "DoubaoWledSkill/1.0"})
        with urllib.request.urlopen(req, timeout=10) as resp:
            img_data = resp.read()
        img = Image.open(io.BytesIO(img_data))
    elif source.startswith("data:"):
        import base64
        header, b64data = source.split(",", 1)
        img_data = base64.b64decode(b64data)
        img = Image.open(io.BytesIO(img_data))
    elif os.path.exists(source):
        img = Image.open(source)
    else:
        raise FileNotFoundError(f"Image source not found or unsupported: {source}")

    if img.mode != "RGB":
        img = img.convert("RGB")
    # Downscale aggressively for speed (max 150x150 = 22500 px max)
    if max(img.size) > max_size:
        img.thumbnail((max_size, max_size), Image.LANCZOS)
    return img


def rgb_to_hsv(r, g, b):
    """Convert RGB (0-255) to HSV (H:0-360, S:0-100, V:0-100)."""
    r, g, b = r / 255.0, g / 255.0, b / 255.0
    mx = max(r, g, b)
    mn = min(r, g, b)
    df = mx - mn
    if mx == mn:
        h = 0
    elif mx == r:
        h = (60 * ((g - b) / df) + 360) % 360
    elif mx == g:
        h = (60 * ((b - r) / df) + 120) % 360
    else:
        h = (60 * ((r - g) / df) + 240) % 360
    s = 100 * (mx - mn) / mx if mx > 0 else 0
    v = 100 * mx
    return h, s, v


def extract_colors_quantize(img, num_colors=5):
    """Use PIL's quantize() for fast color reduction. Returns list of (rgb, count)."""
    # Quantize to small palette (request more than needed, filter later)
    quant_colors = num_colors * 4
    quantized = img.quantize(colors=quant_colors, method=2)  # 2 = MEDIANCUT
    palette = quantized.getpalette()[:quant_colors * 3]
    palette_rgb = [tuple(palette[i:i + 3]) for i in range(0, len(palette), 3)]

    # Count pixels per palette index
    pixels = list(quantized.getdata())
    counts = [0] * quant_colors
    for p in pixels:
        counts[p] += 1
    total = sum(counts)

    # Build (rgb, ratio) list
    result = []
    for i, rgb in enumerate(palette_rgb):
        ratio = counts[i] / total if total > 0 else 0
        if ratio > 0:
            result.append((rgb, ratio))

    # Sort by ratio descending
    result.sort(key=lambda x: x[1], reverse=True)
    return result


def extract_colors_histogram(img, num_colors=5):
    """Fallback: simple 4x4x4 RGB histogram (64 buckets)."""
    pixels = list(img.getdata())
    buckets = {}
    for r, g, b in pixels:
        # Quantize to 4 levels per channel
        key = (r >> 6, g >> 6, b >> 6)
        if key not in buckets:
            buckets[key] = {"r": 0, "g": 0, "b": 0, "count": 0}
        buckets[key]["r"] += r
        buckets[key]["g"] += g
        buckets[key]["b"] += b
        buckets[key]["count"] += 1

    total = sum(b["count"] for b in buckets.values())
    result = []
    for key, b in buckets.items():
        avg_rgb = (b["r"] // b["count"], b["g"] // b["count"], b["b"] // b["count"])
        result.append((avg_rgb, b["count"] / total))
    result.sort(key=lambda x: x[1], reverse=True)
    return result


def analyze_colors(img, num_colors=5, min_saturation=30, min_brightness=20, avoid_overdark=True):
    """Extract dominant colors from image."""
    # Try fast quantize method first
    try:
        raw_colors = extract_colors_quantize(img, num_colors)
    except Exception:
        raw_colors = extract_colors_histogram(img, num_colors)

    if not raw_colors:
        return []

    # Filter colors based on HSV criteria
    colors = []
    for rgb, ratio in raw_colors:
        r, g, b = rgb
        h, s, v = rgb_to_hsv(r, g, b)
        if avoid_overdark and v < min_brightness:
            continue
        colors.append({
            "rgb": [r, g, b],
            "hex": "#{:02X}{:02X}{:02X}".format(r, g, b),
            "ratio": round(ratio, 4),
            "hsv": {"h": round(h, 1), "s": round(s, 1), "v": round(v, 1)}
        })

    # If filtering removed too many, relax criteria
    if len(colors) < 3:
        for rgb, ratio in raw_colors:
            r, g, b = rgb
            h, s, v = rgb_to_hsv(r, g, b)
            entry = {
                "rgb": [r, g, b],
                "hex": "#{:02X}{:02X}{:02X}".format(r, g, b),
                "ratio": round(ratio, 4),
                "hsv": {"h": round(h, 1), "s": round(s, 1), "v": round(v, 1)}
            }
            if entry not in colors:
                colors.append(entry)
                if len(colors) >= num_colors:
                    break

    # Take top N
    result = colors[:num_colors]

    # Normalize ratios
    total_ratio = sum(c["ratio"] for c in result)
    if total_ratio > 0:
        for c in result:
            c["ratio"] = round(c["ratio"] / total_ratio, 4)

    return result


def build_wled_palette(colors):
    """Build WLED custom palette data array from colors.
    Format: [position, R, G, B, position, R, G, B, ...]
    """
    if not colors:
        return [0, 128, 128, 128, 255, 128, 128, 128]

    palette = []
    n = len(colors)
    for i, c in enumerate(colors):
        pos = int(255 * i / max(n - 1, 1)) if n > 1 else 0
        r, g, b = c["rgb"]
        palette.extend([pos, r, g, b])
    if n > 1 and palette[-4] != 255:
        palette[-4] = 255
    return palette


def suggest_recipe(colors, config):
    """Suggest WLED effect/speed/intensity based on color analysis."""
    effect_cfg = config.get("effect_mapping", {})
    if not colors:
        return {
            "fx": effect_cfg.get("default_fx", 9),
            "sx": effect_cfg.get("default_speed", 128),
            "ix": effect_cfg.get("default_intensity", 200),
            "pal": 0,
            "bri": 200,
            "rationale": "Default effect (no colors analyzed)"
        }

    total_ratio = sum(c["ratio"] for c in colors) or 1
    avg_hue = sum(c["hsv"]["h"] * c["ratio"] for c in colors) / total_ratio
    avg_sat = sum(c["hsv"]["s"] * c["ratio"] for c in colors) / total_ratio
    avg_val = sum(c["hsv"]["v"] * c["ratio"] for c in colors) / total_ratio
    hue_range = max(c["hsv"]["h"] for c in colors) - min(c["hsv"]["h"] for c in colors)

    # Theme detection by hue
    if avg_hue < 60 or avg_hue > 330:
        theme = "warm"
        fx_list = effect_cfg.get("sunset_themes", [13, 21, 35])
        fx = fx_list[0] if fx_list else 13
        rationale = f"Warm tones (avg hue {avg_hue:.0f}°) - sunset/fire effect"
    elif 60 <= avg_hue < 180:
        theme = "nature"
        fx_list = effect_cfg.get("nature_themes", [10, 14, 21])
        fx = fx_list[0] if fx_list else 10
        rationale = f"Green/yellow tones (avg hue {avg_hue:.0f}°) - nature/forest effect"
    elif 180 <= avg_hue < 270:
        theme = "cool"
        fx = 9
        rationale = f"Cool blue tones (avg hue {avg_hue:.0f}°) - ocean/sky effect"
    else:
        theme = "party"
        fx_list = effect_cfg.get("party_themes", [6, 11, 12])
        fx = fx_list[0] if fx_list else 6
        rationale = f"Purple/magenta tones (avg hue {avg_hue:.0f}°) - party effect"

    sx = max(50, min(255, int(80 + (100 - avg_sat) * 1.5)))
    ix = max(100, min(255, int(150 + hue_range * 0.3)))
    bri = max(80, min(255, int(100 + avg_val * 1.5)))

    return {
        "fx": fx,
        "sx": sx,
        "ix": ix,
        "pal": 0,
        "bri": bri,
        "theme": theme,
        "rationale": rationale,
        "color_stats": {
            "avg_hue": round(avg_hue, 1),
            "avg_saturation": round(avg_sat, 1),
            "avg_brightness": round(avg_val, 1),
            "hue_range": round(hue_range, 1)
        }
    }


def main():
    if len(sys.argv) < 2:
        print(json.dumps({"success": False, "message": "Usage: analyze_image.py <image_url_or_path> [--num-colors N] [--json]"}, ensure_ascii=False))
        sys.exit(1)

    image_source = sys.argv[1]
    num_colors = 5
    json_only = False

    for i, arg in enumerate(sys.argv[2:], 2):
        if arg == "--num-colors" and i + 1 < len(sys.argv):
            num_colors = int(sys.argv[i + 1])
        elif arg == "--json":
            json_only = True

    config = load_config()
    color_cfg = config.get("color_analysis", {})

    try:
        img = load_image(image_source)
        colors = analyze_colors(
            img,
            num_colors=num_colors,
            min_saturation=color_cfg.get("min_saturation", 30),
            min_brightness=color_cfg.get("min_brightness", 20),
            avoid_overdark=color_cfg.get("avoid_overdark", True)
        )
        palette_data = build_wled_palette(colors)
        recipe_suggestion = suggest_recipe(colors, config)

        result = {
            "success": True,
            "image_source": image_source,
            "image_size": img.size,
            "colors": colors,
            "palette_data": palette_data,
            "recipe_suggestion": recipe_suggestion,
            "wled_state_patch": {
                "on": True,
                "bri": recipe_suggestion.get("bri", 200),
                "seg": [{
                    "fx": recipe_suggestion["fx"],
                    "sx": recipe_suggestion["sx"],
                    "ix": recipe_suggestion["ix"],
                    "pal": 0,
                    "col": [[c["rgb"][0], c["rgb"][1], c["rgb"][2]] for c in colors[:3]]
                }]
            }
        }

        if not json_only:
            print(f"Image: {image_source} ({img.size[0]}x{img.size[1]})")
            print(f"Colors ({len(colors)}):")
            for i, c in enumerate(colors, 1):
                print(f"  {i}. {c['hex']} RGB{tuple(c['rgb'])} - {c['ratio']*100:.1f}%")
            print(f"\nRecipe: FX={recipe_suggestion['fx']} SX={recipe_suggestion['sx']} IX={recipe_suggestion['ix']}")
            print(f"Rationale: {recipe_suggestion['rationale']}")
            print(f"\nPalette: {palette_data}")
            print("\n--- JSON ---")

        print(json.dumps(result, indent=2, ensure_ascii=False))

    except Exception as e:
        error_result = {"success": False, "error": str(e), "image_source": image_source}
        print(json.dumps(error_result, indent=2, ensure_ascii=False))
        sys.exit(1)


if __name__ == "__main__":
    main()
# AI: end
