#!/usr/bin/env python3
# AI: below section was generated by an AI
"""
Apply a light recipe to WLED device via JSON API.
Handles UDP realtime mode takeover, segment config by layout, RGBW support.

Usage:
    python3 apply_recipe.py <recipe_json_file>
    python3 apply_recipe.py <recipe_json_file> --dry-run    # preview without applying
    python3 apply_recipe.py --stdin                          # read recipe from stdin

Recipe JSON format (compatible with analyze_image.py output):
{
  "name": "Jasmine Blooms",
  "colors": [[r,g,b], ...],          # 3 primary colors
  "palette_data": [pos,r,g,b,...],   # WLED custom palette (optional)
  "fx": 10,                          # effect ID
  "sx": 176,                         # speed
  "ix": 165,                         # intensity
  "bri": 200,                        # brightness
  "pal": 0                           # palette ID (0=default, will use custom if uploaded)
}

Output: JSON with {success, applied_state, wled_response, message}
"""
import json
import os
import sys
import urllib.request
import urllib.error

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
CONFIG_PATH = os.path.join(os.path.dirname(SCRIPT_DIR), "config.json")


def load_config():
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def get_wled_ip():
    """Get WLED IP from cache or run discovery."""
    cache_path = os.path.join(SCRIPT_DIR, ".wled_cache.json")
    if os.path.exists(cache_path):
        with open(cache_path, "r") as f:
            cache = json.load(f)
            if cache.get("ip"):
                return cache["ip"]
    # Fallback to config
    config = load_config()
    return config.get("wled", {}).get("ip", "192.168.2.66")


def wled_request(ip, path, method="GET", data=None, timeout=5):
    """Make HTTP request to WLED device."""
    url = f"http://{ip}{path}"
    req = urllib.request.Request(url, headers={"User-Agent": "DoubaoWledSkill/1.0"})
    if method == "POST" and data is not None:
        req.data = json.dumps(data).encode("utf-8")
        req.add_header("Content-Type", "application/json")
        req.method = "POST"
    else:
        req.method = method

    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            body = resp.read().decode("utf-8")
            try:
                return json.loads(body) if body else {}
            except json.JSONDecodeError:
                return {"raw": body}
    except urllib.error.HTTPError as e:
        return {"error": f"HTTP {e.code}", "message": str(e)}
    except Exception as e:
        return {"error": str(e)}


def stop_udp_realtime(ip):
    """Stop UDP realtime mode so JSON API can take control.
    WLED 0.14+ respects {'live':false} to force exit realtime.
    """
    # Send a state update to force exit live mode
    result = wled_request(ip, "/json/state", method="POST", data={"live": False, "on": True})
    return result


def build_segments(recipe, config):
    """Build segment configuration based on layout type."""
    layout = config.get("layout", {})
    layout_type = layout.get("type", "linear")
    total_leds = layout.get("total_leds", 56)
    colors = recipe.get("colors", [[128, 128, 128]])

    # Ensure colors is list of lists
    if colors and isinstance(colors[0], int):
        colors = [colors]

    # Pad colors to 3 slots
    while len(colors) < 3:
        colors.append([0, 0, 0])

    fx = recipe.get("fx", 9)
    sx = recipe.get("sx", 128)
    ix = recipe.get("ix", 200)
    pal = recipe.get("pal", 0)
    bri_seg = recipe.get("seg_bri", 255)

    if layout_type == "tv_backlight" and layout.get("segment_strategy") == "per_edge":
        # Create 4 segments for TV backlight (top, right, bottom, left)
        edges = layout.get("edges", {})
        top = edges.get("top", total_leds // 4)
        right = edges.get("right", total_leds // 4)
        bottom = edges.get("bottom", total_leds // 4)
        left = edges.get("left", total_leds // 4)
        direction = layout.get("direction", "cw")
        start_corner = layout.get("start_corner", "top_left")

        # Calculate segment boundaries based on start corner and direction
        # For CW from top_left: top(0-top), right(top-top+right), bottom, left
        segments = []
        pos = 0
        edge_order = []
        if direction == "cw":
            if start_corner == "top_left":
                edge_order = [("top", top), ("right", right), ("bottom", bottom), ("left", left)]
            elif start_corner == "top_right":
                edge_order = [("right", right), ("bottom", bottom), ("left", left), ("top", top)]
            elif start_corner == "bottom_right":
                edge_order = [("bottom", bottom), ("left", left), ("top", top), ("right", right)]
            else:  # bottom_left
                edge_order = [("left", left), ("top", top), ("right", right), ("bottom", bottom)]
        else:  # ccw
            if start_corner == "top_left":
                edge_order = [("left", left), ("bottom", bottom), ("right", right), ("top", top)]
            else:
                edge_order = [("top", top), ("right", right), ("bottom", bottom), ("left", left)]

        for idx, (edge_name, length) in enumerate(edge_order):
            if length <= 0:
                continue
            # Alternate colors per edge for variety
            edge_color_idx = idx % min(len(colors), 3)
            segments.append({
                "id": idx,
                "start": pos,
                "stop": pos + length,
                "len": length,
                "on": True,
                "bri": bri_seg,
                "fx": fx,
                "sx": sx,
                "ix": ix,
                "pal": pal,
                "col": [colors[edge_color_idx], colors[(edge_color_idx + 1) % 3], colors[(edge_color_idx + 2) % 3]]
            })
            pos += length

        # If we have unused LEDs, extend last segment
        if pos < total_leds and segments:
            segments[-1]["stop"] = total_leds
            segments[-1]["len"] = total_leds - segments[-1]["start"]

        return segments
    else:
        # Single segment for linear/ring layouts
        return [{
            "id": 0,
            "start": 0,
            "stop": total_leds,
            "len": total_leds,
            "on": True,
            "bri": bri_seg,
            "fx": fx,
            "sx": sx,
            "ix": ix,
            "pal": pal,
            "col": [colors[0], colors[1] if len(colors) > 1 else [0,0,0], colors[2] if len(colors) > 2 else [0,0,0]]
        }]


def apply_recipe(recipe, dry_run=False):
    """Apply recipe to WLED device."""
    config = load_config()
    ip = get_wled_ip()

    # Validate recipe
    if not recipe.get("colors") and not recipe.get("fx"):
        return {"success": False, "message": "Recipe must contain colors or fx"}

    # Build state update
    bri = recipe.get("bri", 200)
    segments = build_segments(recipe, config)

    # First: delete extra segments (keep only what we need)
    # Then: set up our segments
    state_patch = {
        "on": True,
        "bri": bri,
        "transition": 0,
        "live": False,  # Force exit UDP realtime
        "mainseg": 0,
        "seg": segments
    }

    if dry_run:
        return {
            "success": True,
            "dry_run": True,
            "ip": ip,
            "state_patch": state_patch,
            "message": f"Would apply recipe '{recipe.get('name', 'unnamed')}' to {ip}"
        }

    # Step 1: Stop UDP realtime mode
    stop_result = stop_udp_realtime(ip)

    # Step 2: Apply state
    apply_result = wled_request(ip, "/json/state", method="POST", data=state_patch)

    # Step 3: Verify by reading state
    verify = wled_request(ip, "/json/state", method="GET")

    return {
        "success": True,
        "ip": ip,
        "recipe_name": recipe.get("name", "unnamed"),
        "state_patch": state_patch,
        "applied": apply_result,
        "verified_state": {
            "on": verify.get("on"),
            "bri": verify.get("bri"),
            "live": verify.get("live"),
            "mainseg": verify.get("mainseg"),
            "seg_count": len(verify.get("seg", []))
        },
        "message": f"Recipe '{recipe.get('name', 'unnamed')}' applied to WLED at {ip}"
    }


def main():
    dry_run = "--dry-run" in sys.argv
    use_stdin = "--stdin" in sys.argv

    if use_stdin:
        recipe_str = sys.stdin.read()
    elif len(sys.argv) < 2 or sys.argv[1].startswith("--"):
        print(json.dumps({"success": False, "message": "Usage: apply_recipe.py <recipe_json_file> [--dry-run]"}, ensure_ascii=False))
        sys.exit(1)
    else:
        recipe_file = sys.argv[1]
        if not os.path.exists(recipe_file):
            print(json.dumps({"success": False, "message": f"Recipe file not found: {recipe_file}"}, ensure_ascii=False))
            sys.exit(1)
        with open(recipe_file, "r", encoding="utf-8") as f:
            recipe_str = f.read()

    try:
        recipe = json.loads(recipe_str)
    except json.JSONDecodeError as e:
        print(json.dumps({"success": False, "message": f"Invalid JSON: {e}"}, ensure_ascii=False))
        sys.exit(1)

    result = apply_recipe(recipe, dry_run=dry_run)
    print(json.dumps(result, indent=2, ensure_ascii=False))
    sys.exit(0 if result.get("success") else 1)


if __name__ == "__main__":
    main()
# AI: end
