#!/usr/bin/env python3
# AI: below section was generated by an AI
"""
One-shot pipeline: analyze multiple images -> merge colors -> apply dynamic recipe to WLED.
This is the RECOMMENDED workflow for creating dynamic, continuously animating light effects.

The merged recipe uses a single dynamic FX (Pacifica/Sunset/Flow) with merged colors
from all images, ensuring smooth continuous animation without playlist dependency.

Usage:
    python3 apply_dynamic_recipe.py <url1> <url2> [url3] [url4] --scene "Scene Name"
    python3 apply_dynamic_recipe.py --urls-file urls.txt --scene "Jasmine Blooms"
    python3 apply_dynamic_recipe.py <url1> <url2> --scene "Sunset" --save-preset

Output: JSON with {success, scene, colors, fx, message}
"""
import json
import os
import sys
import time

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, SCRIPT_DIR)

from analyze_multi_images import analyze_multi_images
from apply_recipe import apply_recipe, stop_udp_realtime, get_wled_ip, wled_request


def check_and_warn_live(ip):
    """Check if UDP realtime is active and warn."""
    state = wled_request(ip, "/json/state", method="GET", timeout=3)
    if isinstance(state, dict) and state.get("live"):
        # Force stop UDP realtime
        stop_udp_realtime(ip)
        time.sleep(0.5)
        return True
    return False


def apply_dynamic_recipe(image_sources, scene_name, save_preset=False):
    """Full pipeline: multi-image analysis -> merged recipe -> apply to WLED."""
    # Step 1: Analyze multiple images
    analysis = analyze_multi_images(image_sources, scene_name)
    if not analysis.get("success"):
        return analysis

    merged_recipe = analysis.get("merged_recipe")
    if not merged_recipe:
        return {"success": False, "message": "No merged recipe generated"}

    # Step 2: Check WLED connection and live status
    ip = get_wled_ip()
    if not ip:
        return {"success": False, "message": "WLED IP not configured. Run discover_wled.py first"}

    live_was_active = check_and_warn_live(ip)

    # Step 3: Apply merged recipe
    apply_result = apply_recipe(merged_recipe)
    if not apply_result.get("success"):
        return {"success": False, "analysis": analysis, "apply_result": apply_result,
                "message": f"Failed to apply recipe: {apply_result.get('message')}"}

    # Step 4: Optionally save as preset
    preset_id = None
    if save_preset:
        time.sleep(0.5)
        try:
            from save_preset import find_free_preset_id, save_preset as save_preset_fn
            from apply_recipe import load_config
            config = load_config()
            storage_cfg = config.get("recipe_storage", {})
            pid_start = storage_cfg.get("preset_id_start", 100)
            pid_end = storage_cfg.get("preset_id_end", 250)
            preset_id = find_free_preset_id(ip, pid_start, pid_end)
            if preset_id:
                save_result = save_preset_fn(preset_id, scene_name)
                if not save_result.get("success"):
                    preset_id = None
        except Exception as e:
            pass

    # Step 5: Verify final state
    time.sleep(0.5)
    verify = wled_request(ip, "/json/state", method="GET", timeout=3)
    active_segs = [s for s in verify.get("seg", []) if s.get("len", 0) > 0]
    seg0 = active_segs[0] if active_segs else {}

    return {
        "success": True,
        "scene": scene_name,
        "ip": ip,
        "image_count": len(image_sources),
        "merged_colors": merged_recipe.get("colors"),
        "merged_colors_hex": merged_recipe.get("merged_colors_hex"),
        "fx": merged_recipe.get("fx"),
        "sx": merged_recipe.get("sx"),
        "ix": merged_recipe.get("ix"),
        "bri": merged_recipe.get("bri"),
        "theme": merged_recipe.get("theme"),
        "rationale": merged_recipe.get("rationale"),
        "live_was_active": live_was_active,
        "preset_saved": preset_id is not None,
        "preset_id": preset_id,
        "verified": {
            "on": verify.get("on"),
            "live": verify.get("live"),
            "fx": seg0.get("fx"),
            "sx": seg0.get("sx"),
            "col": seg0.get("col", [[]])[0] if seg0.get("col") else None
        },
        "message": (f"Dynamic recipe '{scene_name}' applied! "
                    f"FX={merged_recipe['fx']} with {len(merged_recipe['colors'])} merged colors. "
                    f"Effect will animate continuously and loop automatically. "
                    f"{'Saved as preset ' + str(preset_id) + '.' if preset_id else 'Not saved as preset.'}")
    }


def main():
    if "--help" in sys.argv or "-h" in sys.argv or len(sys.argv) < 2:
        print(__doc__)
        sys.exit(0)

    scene_name = "Dynamic Scene"
    save_preset = False
    urls_file = None
    image_sources = []

    i = 1
    while i < len(sys.argv):
        arg = sys.argv[i]
        if arg == "--scene" and i + 1 < len(sys.argv):
            scene_name = sys.argv[i + 1]; i += 2
        elif arg == "--save-preset":
            save_preset = True; i += 1
        elif arg == "--urls-file" and i + 1 < len(sys.argv):
            urls_file = sys.argv[i + 1]; i += 2
        else:
            image_sources.append(arg); i += 1

    if urls_file:
        with open(urls_file, "r") as f:
            image_sources = [line.strip() for line in f if line.strip() and not line.startswith("#")]

    if not image_sources:
        print(json.dumps({"success": False, "message": "No image URLs provided"}, ensure_ascii=False))
        sys.exit(1)

    if len(image_sources) > 6:
        image_sources = image_sources[:6]

    result = apply_dynamic_recipe(image_sources, scene_name, save_preset=save_preset)
    print(json.dumps(result, indent=2, ensure_ascii=False))
    sys.exit(0 if result.get("success") else 1)


if __name__ == "__main__":
    main()
# AI: end
