#!/usr/bin/env python3
# AI: below section was generated by an AI
"""
Build a WLED playlist from multiple recipes and apply it for infinite looping.
Creates sub-presets for each recipe, then a playlist preset that cycles through them.

WLED Playlist API (0.14+):
    Playlist is stored as a preset with "playlist" field:
    {
      "n": "My Playlist",
      "playlist": {
        "ps": [101, 102, 103, 104],     # sub-preset IDs
        "dur": [15000, 15000, 15000, 15000],  # duration per preset (ms)
        "transition": 500,               # transition between presets (ms)
        "repeat": 0,                     # 0 = infinite loop
        "end": 0                         # 0 = stop at end, 1 = turn off, 2 = restart
      }
    }

Usage:
    python3 build_playlist.py <analysis_json> [--scene "Scene Name"] [--duration 60]
    python3 build_playlist.py /tmp/multi_analysis.json --scene "Jasmine Blooms" --duration 60
    python3 build_playlist.py --recipes-file recipes.json --scene "Sunset" --apply

Output: JSON with {success, playlist_id, sub_preset_ids, message}
"""
import json
import os
import sys
import time
import urllib.request
import urllib.error

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SKILL_DIR = os.path.dirname(SCRIPT_DIR)
sys.path.insert(0, SCRIPT_DIR)

from apply_recipe import get_wled_ip, wled_request, stop_udp_realtime, build_segments, load_config


def check_live_status(ip):
    """Check if UDP realtime mode is active (e.g. SYMI-Ambient app pushing frames)."""
    state = wled_request(ip, "/json/state", method="GET")
    return state.get("live", False) if isinstance(state, dict) and "error" not in state else None


def get_device_led_count(ip):
    """Get actual LED count from WLED device."""
    info = wled_request(ip, "/json/info", method="GET", timeout=3)
    if isinstance(info, dict) and "leds" in info:
        return info.get("leds", {}).get("count", 0)
    return 0


def save_sub_preset(ip, preset_id, name, recipe, config, device_led_count):
    """Apply a recipe and save it as a sub-preset.
    Uses direct state set + psave to avoid relying on file upload.
    """
    # Build segment state from recipe
    segments = build_segments(recipe, config, device_led_count)
    bri = recipe.get("bri", 200)

    # Step 1: Apply the recipe state
    state_patch = {
        "on": True,
        "bri": bri,
        "transition": 0,
        "live": False,
        "mainseg": 0,
        "seg": segments
    }
    apply_result = wled_request(ip, "/json/state", method="POST", data=state_patch, timeout=5)
    if "error" in apply_result:
        return {"success": False, "preset_id": preset_id, "error": str(apply_result["error"])}

    # Small delay to let WLED process the state
    time.sleep(0.3)

    # Step 2: Save current state as preset
    save_result = wled_request(ip, "/json/state", method="POST",
                               data={"psave": preset_id, "n": name}, timeout=5)
    return {
        "success": "error" not in save_result,
        "preset_id": preset_id,
        "name": name,
        "fx": recipe.get("fx"),
        "colors": recipe.get("colors"),
        "save_result": save_result
    }


def upload_presets_file(ip, presets_dict):
    """Upload complete presets.json to WLED via multipart file upload.
    This is the ONLY way to save playlist presets - psave API only saves current state.
    """
    content = json.dumps(presets_dict, indent=2, ensure_ascii=False)
    boundary = "----DoubaoWledPlaylistBoundary"
    body = (
        f"--{boundary}\r\n"
        f'Content-Disposition: form-data; name="file"; filename="presets.json"\r\n'
        f"Content-Type: application/json\r\n\r\n"
        f"{content}\r\n"
        f"--{boundary}--\r\n"
    ).encode("utf-8")

    url = f"http://{ip}/upload"
    req = urllib.request.Request(url, data=body, method="POST")
    req.add_header("Content-Type", f"multipart/form-data; boundary={boundary}")
    req.add_header("User-Agent", "DoubaoWledSkill/1.0")

    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            resp_body = resp.read().decode("utf-8")
            return {"success": True, "response": resp_body[:200]}
    except urllib.error.HTTPError as e:
        # Try /edit as fallback
        return _try_edit_upload(ip, content)
    except Exception as e:
        return _try_edit_upload(ip, content)


def _try_edit_upload(ip, content):
    """Fallback: upload via /edit endpoint."""
    boundary = "----DoubaoWledPlaylistBoundary"
    body = (
        f"--{boundary}\r\n"
        f'Content-Disposition: form-data; name="path"\r\n\r\n'
        f"/presets.json\r\n"
        f"--{boundary}\r\n"
        f'Content-Disposition: form-data; name="file"; filename="presets.json"\r\n'
        f"Content-Type: application/json\r\n\r\n"
        f"{content}\r\n"
        f"--{boundary}--\r\n"
    ).encode("utf-8")

    url = f"http://{ip}/edit"
    req = urllib.request.Request(url, data=body, method="POST")
    req.add_header("Content-Type", f"multipart/form-data; boundary={boundary}")
    req.add_header("User-Agent", "DoubaoWledSkill/1.0")

    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            resp_body = resp.read().decode("utf-8")
            return {"success": True, "response": resp_body[:200], "method": "edit"}
    except Exception as e:
        return {"success": False, "error": str(e)}


def save_playlist_preset(ip, playlist_id, name, sub_preset_ids, durations, transition_ms=500, repeat=0):
    """Save a playlist preset by directly editing /presets.json file.
    psave API only saves current state, not playlist metadata.
    We must read presets.json, inject playlist entry, and upload back.
    """
    # Step 1: Read current presets.json
    current_presets = wled_request(ip, "/presets.json", method="GET", timeout=5)
    if "error" in current_presets or not isinstance(current_presets, dict):
        current_presets = {}

    # Step 2: Create playlist entry (replaces any existing preset at this ID)
    playlist_entry = {
        "n": name,
        "playlist": {
            "ps": sub_preset_ids,
            "dur": durations,
            "transition": transition_ms,
            "repeat": repeat,
            "end": 0,
            "r": False  # sequential, no shuffle
        }
    }

    # Step 3: Inject playlist entry into presets dict
    current_presets[str(playlist_id)] = playlist_entry

    # Step 4: Upload modified presets.json back to WLED
    upload_result = upload_presets_file(ip, current_presets)

    return {
        "success": upload_result.get("success", False),
        "playlist_id": playlist_id,
        "name": name,
        "sub_presets": sub_preset_ids,
        "durations": durations,
        "repeat": repeat,
        "upload_result": upload_result,
        "message": f"Playlist saved to presets.json (ID {playlist_id})" if upload_result.get("success") else f"Upload failed: {upload_result.get('error', 'unknown')}"
    }


def activate_playlist(ip, playlist_id):
    """Activate the playlist preset."""
    result = wled_request(ip, "/json/state", method="POST",
                          data={"ps": playlist_id, "on": True}, timeout=5)
    return {"success": "error" not in result, "playlist_id": playlist_id, "result": result}


def build_and_apply_playlist(analysis_data, scene_name=None, total_duration=60, apply=True):
    """Full pipeline: create sub-presets, build playlist, activate it."""
    # Load analysis data
    if isinstance(analysis_data, str):
        # File path
        if not os.path.exists(analysis_data):
            return {"success": False, "message": f"Analysis file not found: {analysis_data}"}
        with open(analysis_data, "r", encoding="utf-8") as f:
            analysis = json.load(f)
    else:
        analysis = analysis_data

    if not analysis.get("success"):
        return {"success": False, "message": "Analysis data is not successful"}

    recipes = analysis.get("recipes", [])
    if not recipes:
        return {"success": False, "message": "No recipes in analysis data"}

    scene_name = scene_name or analysis.get("scene", "Untitled Scene")
    ip = get_wled_ip()
    if not ip:
        return {"success": False, "message": "WLED IP not configured. Run discover_wled.py first"}

    config = load_config()
    storage_cfg = config.get("recipe_storage", {})
    preset_id_start = storage_cfg.get("preset_id_start", 100)
    preset_id_end = storage_cfg.get("preset_id_end", 250)

    # Step 0: Check live status (warn if UDP realtime active)
    live_status = check_live_status(ip)
    if live_status is True:
        # Force stop UDP realtime to take control
        stop_udp_realtime(ip)
        time.sleep(0.5)

    # Get device LED count
    device_led_count = get_device_led_count(ip)

    # Step 1: Save each recipe as a sub-preset
    sub_preset_ids = []
    durations = []
    per_scene_ms = (total_duration * 1000) // len(recipes)

    steps = []
    for i, recipe in enumerate(recipes):
        sub_id = preset_id_start + 1 + i  # 101, 102, 103, ...
        if sub_id > preset_id_end:
            return {"success": False, "message": f"Ran out of preset IDs (max {preset_id_end})"}
        sub_name = f"{scene_name} - {i + 1}"
        result = save_sub_preset(ip, sub_id, sub_name, recipe, config, device_led_count)
        steps.append({"step": f"save_sub_preset_{i+1}", "result": result})
        if result.get("success"):
            sub_preset_ids.append(sub_id)
            durations.append(per_scene_ms)
        else:
            return {"success": False, "steps": steps,
                    "message": f"Failed to save sub-preset {sub_id}: {result.get('error', 'unknown')}"}

    # Step 2: Save playlist preset
    playlist_id = preset_id_start  # 100
    playlist_result = save_playlist_preset(
        ip, playlist_id, scene_name, sub_preset_ids, durations,
        transition_ms=500, repeat=0
    )
    steps.append({"step": "save_playlist", "result": playlist_result})

    if not playlist_result.get("success"):
        return {"success": False, "steps": steps,
                "message": f"Failed to save playlist: {playlist_result}"}

    # Step 3: Activate playlist
    if apply:
        time.sleep(0.5)
        activate_result = activate_playlist(ip, playlist_id)
        steps.append({"step": "activate_playlist", "result": activate_result})

    # Verify final state
    verify = wled_request(ip, "/json/state", method="GET", timeout=3)

    return {
        "success": True,
        "scene": scene_name,
        "ip": ip,
        "playlist_id": playlist_id,
        "sub_preset_ids": sub_preset_ids,
        "durations_sec": [d // 1000 for d in durations],
        "total_duration_sec": sum(durations) // 1000,
        "repeat": "infinite (0)",
        "live_status_before": live_status,
        "verified_state": {
            "on": verify.get("on"),
            "ps": verify.get("ps"),
            "pl": verify.get("pl"),
            "live": verify.get("live")
        },
        "steps": steps,
        "message": (f"Playlist '{scene_name}' created with {len(sub_preset_ids)} scenes, "
                    f"each {per_scene_ms//1000}s, total {sum(durations)//1000}s, infinite loop. "
                    f"Playlist ID: {playlist_id}, Sub-presets: {sub_preset_ids}")
    }


def main():
    if "--help" in sys.argv or "-h" in sys.argv or len(sys.argv) < 2:
        print(__doc__)
        sys.exit(0)

    analysis_file = None
    scene_name = None
    duration = 60
    apply_flag = True
    recipes_file = None

    i = 1
    while i < len(sys.argv):
        arg = sys.argv[i]
        if arg == "--scene" and i + 1 < len(sys.argv):
            scene_name = sys.argv[i + 1]; i += 2
        elif arg == "--duration" and i + 1 < len(sys.argv):
            duration = int(sys.argv[i + 1]); i += 2
        elif arg == "--recipes-file" and i + 1 < len(sys.argv):
            recipes_file = sys.argv[i + 1]; i += 2
        elif arg == "--no-apply":
            apply_flag = False; i += 1
        else:
            analysis_file = arg; i += 1

    if recipes_file:
        analysis_file = recipes_file

    if not analysis_file:
        print(json.dumps({"success": False, "message": "Usage: build_playlist.py <analysis_json> [--scene NAME] [--duration 60]"}, ensure_ascii=False))
        sys.exit(1)

    result = build_and_apply_playlist(analysis_file, scene_name=scene_name,
                                      total_duration=duration, apply=apply_flag)
    print(json.dumps(result, indent=2, ensure_ascii=False))
    sys.exit(0 if result.get("success") else 1)


if __name__ == "__main__":
    main()
# AI: end
