#!/usr/bin/env python3
# AI: below section was generated by an AI
"""
WLED mDNS auto-discovery with cache.
Resolves WLED device IP via mDNS hostname, caches result to avoid repeated scans.
Re-scans only when cached IP fails health check.

Usage:
    python3 discover_wled.py                     # discover or use cache
    python3 discover_wled.py --force             # force re-scan, ignore cache
    python3 discover_wled.py --health-only       # only check cached IP health
    python3 discover_wled.py --list              # list all WLED devices on LAN

Output: JSON with {success, ip, mdns, source, info}
"""
import json
import os
import socket
import sys
import time
import urllib.request

CONFIG_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "config.json")
CACHE_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".wled_cache.json")
HEALTH_TIMEOUT = 2
MDNS_SCAN_TIMEOUT = 4


def load_config():
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def load_cache():
    if not os.path.exists(CACHE_PATH):
        return None
    try:
        with open(CACHE_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return None


def save_cache(cache_data):
    with open(CACHE_PATH, "w", encoding="utf-8") as f:
        json.dump(cache_data, f, indent=2, ensure_ascii=False)


def health_check(ip, timeout=HEALTH_TIMEOUT):
    """Check if WLED device is reachable and responsive."""
    try:
        url = f"http://{ip}/json/info"
        req = urllib.request.Request(url, headers={"User-Agent": "DoubaoWledSkill/1.0"})
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            info = json.loads(resp.read().decode("utf-8"))
            # Validate it's really a WLED device
            if "ver" in info and "leds" in info:
                return True, info
        return False, None
    except Exception:
        return False, None


def resolve_mdns(mdns_name):
    """Resolve mDNS hostname to IP address using socket.gethostbyname."""
    # Try both .local and raw name
    candidates = []
    if mdns_name.endswith(".local"):
        candidates.append(mdns_name)
        candidates.append(mdns_name[:-6])  # without .local
    else:
        candidates.append(f"{mdns_name}.local")
        candidates.append(mdns_name)

    for candidate in candidates:
        try:
            ip = socket.gethostbyname(candidate)
            if ip:
                return ip, candidate
        except socket.gaierror:
            continue
        except Exception:
            continue
    return None, None


def scan_lan_wled(timeout=MDNS_SCAN_TIMEOUT):
    """Scan LAN for WLED devices via UDP multicast DNS query.
    Fallback method using raw socket if zeroconf is not available.
    Returns list of (ip, mdns_name) tuples.
    """
    devices = []
    # Method 1: Try socket multicast DNS query
    try:
        import struct
        # mDNS multicast address
        mDNS_ADDR = "224.0.0.251"
        mDNS_PORT = 5353
        # Build DNS query for _wled._tcp.local
        query = (
            b"\x00\x00"  # Transaction ID
            b"\x01\x00"  # Flags (standard query)
            b"\x00\x01"  # Questions: 1
            b"\x00\x00"  # Answer RRs: 0
            b"\x00\x00"  # Authority RRs: 0
            b"\x00\x00"  # Additional RRs: 0
            b"\x05_wled\x04_tcp\x05local\x00"  # _wled._tcp.local
            b"\x00\x0c"  # Type: PTR
            b"\x00\x01"  # Class: IN
        )
        sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        sock.settimeout(timeout)
        sock.sendto(query, (mDNS_ADDR, mDNS_PORT))
        start = time.time()
        while time.time() - start < timeout:
            try:
                data, addr = sock.recvfrom(4096)
                # Parse response to find WLED instance names
                # Look for "wled-" pattern in response
                text = data.decode("latin-1")
                import re
                matches = re.findall(r"wled-[a-f0-9]{6}", text)
                for m in matches:
                    ip, _ = resolve_mdns(m)
                    if ip:
                        devices.append((ip, m))
            except socket.timeout:
                break
            except Exception:
                continue
        sock.close()
    except Exception:
        pass

    # Method 2: Common subnet scan fallback (192.168.x.x)
    if not devices:
        try:
            local_ip = socket.gethostbyname(socket.gethostname())
            if local_ip.startswith("192.168."):
                subnet = ".".join(local_ip.split(".")[:3])
                # Scan common WLED ports in parallel-ish (sequential but fast)
                for last_octet in range(1, 255):
                    ip = f"{subnet}.{last_octet}"
                    ok, _ = health_check(ip, timeout=0.3)
                    if ok:
                        devices.append((ip, "unknown"))
                        break  # Found one, stop scanning
        except Exception:
            pass

    # Deduplicate
    seen = set()
    unique = []
    for ip, name in devices:
        if ip not in seen:
            seen.add(ip)
            unique.append((ip, name))
    return unique


def discover(force=False, health_only=False):
    """Main discovery flow: cache -> health check -> mDNS resolve -> LAN scan."""
    config = load_config()
    wled_cfg = config.get("wled", {})

    # Step 1: Try cached IP first (unless force)
    if not force and not health_only:
        cache = load_cache()
        if cache and cache.get("ip"):
            ok, info = health_check(cache["ip"])
            if ok:
                return {
                    "success": True,
                    "ip": cache["ip"],
                    "mdns": cache.get("mdns_name", ""),
                    "source": "cache",
                    "info": _summarize_info(info),
                    "message": "WLED found from cache"
                }
            # Cache invalid, fall through to discovery

    if health_only:
        cache = load_cache()
        if not cache:
            return {"success": False, "message": "No cached IP to check"}
        ok, info = health_check(cache.get("ip"))
        return {"success": ok, "ip": cache.get("ip"), "info": _summarize_info(info) if ok else None}

    # Step 2: Try config IP
    config_ip = wled_cfg.get("ip")
    if config_ip:
        ok, info = health_check(config_ip)
        if ok:
            save_cache({"ip": config_ip, "mdns_name": wled_cfg.get("mdns_name", ""), "ts": int(time.time())})
            return {
                "success": True,
                "ip": config_ip,
                "mdns": wled_cfg.get("mdns_name", ""),
                "source": "config",
                "info": _summarize_info(info),
                "message": "WLED found from config IP"
            }

    # Step 3: Try mDNS resolve
    mdns_name = wled_cfg.get("mdns_full") or wled_cfg.get("mdns_name")
    if mdns_name:
        ip, resolved_name = resolve_mdns(mdns_name)
        if ip:
            ok, info = health_check(ip)
            if ok:
                save_cache({"ip": ip, "mdns_name": resolved_name, "ts": int(time.time())})
                return {
                    "success": True,
                    "ip": ip,
                    "mdns": resolved_name,
                    "source": "mdns",
                    "info": _summarize_info(info),
                    "message": "WLED found via mDNS resolution"
                }

    # Step 4: Full LAN scan
    devices = scan_lan_wled()
    if devices:
        ip, name = devices[0]
        ok, info = health_check(ip)
        if ok:
            save_cache({"ip": ip, "mdns_name": name, "ts": int(time.time())})
            return {
                "success": True,
                "ip": ip,
                "mdns": name,
                "source": "scan",
                "info": _summarize_info(info),
                "message": f"WLED found via LAN scan ({len(devices)} device(s) found)"
            }

    return {
        "success": False,
        "message": "No WLED device found. Please check network or provide IP in config.json"
    }


def _summarize_info(info):
    """Extract key info from WLED /json/info response."""
    if not info:
        return None
    return {
        "version": info.get("ver", ""),
        "name": info.get("name", ""),
        "leds": {
            "count": info.get("leds", {}).get("count", 0),
            "rgbw": info.get("leds", {}).get("rgbw", False),
            "maxseg": info.get("leds", {}).get("maxseg", 0)
        },
        "fxcount": info.get("fxcount", 0),
        "palcount": info.get("palcount", 0),
        "live": info.get("live", False)
    }


def list_devices():
    """List all WLED devices on LAN."""
    devices = scan_lan_wled()
    result = []
    for ip, name in devices:
        ok, info = health_check(ip)
        result.append({
            "ip": ip,
            "mdns": name,
            "online": ok,
            "info": _summarize_info(info) if ok else None
        })
    return {"success": True, "devices": result, "count": len(result)}


if __name__ == "__main__":
    if "--help" in sys.argv or "-h" in sys.argv:
        print(__doc__)
        sys.exit(0)

    force = "--force" in sys.argv
    health_only = "--health-only" in sys.argv
    list_mode = "--list" in sys.argv

    if list_mode:
        result = list_devices()
    else:
        result = discover(force=force, health_only=health_only)

    print(json.dumps(result, indent=2, ensure_ascii=False))
    sys.exit(0 if result.get("success") else 1)
# AI: end
