#!/usr/bin/env python3
# AI: below section was generated by an AI
"""
Export a light recipe as a portable JSON file for sharing and reuse.
Combines color analysis + recipe suggestion + palette data into a single file.

Usage:
    python3 export_recipe.py --name "Jasmine Blooms" --analysis <analyze_output.json> [--output recipes/jasmine.json]
    python3 export_recipe.py --name "Sunset" --colors "[[255,100,0],[255,200,50]]" --fx 13
    python3 export_recipe.py --list                # list all saved recipes

Recipe JSON format (portable, can be shared and imported):
{
  "name": "Jasmine Blooms",
  "description": "Light green and white tones from jasmine flowers",
  "version": "1.0",
  "created_at": "2026-07-29T10:00:00",
  "source_image": "url_or_path",
  "colors": [[r,g,b], ...],
  "palette_data": [pos,r,g,b,...],
  "fx": 10,
  "sx": 176,
  "ix": 165,
  "bri": 200,
  "pal": 0,
  "theme": "nature",
  "rationale": "Green/yellow tones - nature/forest effect"
}
"""
import json
import os
import sys
from datetime import datetime

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SKILL_DIR = os.path.dirname(SCRIPT_DIR)
CONFIG_PATH = os.path.join(SKILL_DIR, "config.json")
RECIPES_DIR = os.path.join(SKILL_DIR, "recipes")


def load_config():
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def list_recipes():
    """List all saved recipe files."""
    if not os.path.exists(RECIPES_DIR):
        return []
    recipes = []
    for fname in sorted(os.listdir(RECIPES_DIR)):
        if fname.endswith(".json"):
            fpath = os.path.join(RECIPES_DIR, fname)
            try:
                with open(fpath, "r", encoding="utf-8") as f:
                    recipe = json.load(f)
                recipes.append({
                    "file": fname,
                    "path": fpath,
                    "name": recipe.get("name", "unnamed"),
                    "fx": recipe.get("fx"),
                    "theme": recipe.get("theme", ""),
                    "created_at": recipe.get("created_at", "")
                })
            except Exception:
                continue
    return recipes


def export_recipe(name, analysis=None, colors=None, fx=None, sx=None, ix=None, bri=None, output=None, description=""):
    """Export a recipe JSON file."""
    config = load_config()
    storage = config.get("recipe_storage", {})

    recipe = {
        "name": name,
        "description": description,
        "version": "1.0",
        "created_at": datetime.now().isoformat(timespec="seconds"),
        "format": "doubao-wled-recipe-v1"
    }

    # Load from analysis output
    if analysis:
        with open(analysis, "r", encoding="utf-8") as f:
            analysis_data = json.load(f)
        recipe["source_image"] = analysis_data.get("image_source", "")
        recipe["colors"] = [c["rgb"] for c in analysis_data.get("colors", [])]
        recipe["palette_data"] = analysis_data.get("palette_data", [])
        suggestion = analysis_data.get("recipe_suggestion", {})
        recipe["fx"] = fx if fx is not None else suggestion.get("fx", 9)
        recipe["sx"] = sx if sx is not None else suggestion.get("sx", 128)
        recipe["ix"] = ix if ix is not None else suggestion.get("ix", 200)
        recipe["bri"] = bri if bri is not None else suggestion.get("bri", 200)
        recipe["pal"] = 0  # Use custom palette
        recipe["theme"] = suggestion.get("theme", "")
        recipe["rationale"] = suggestion.get("rationale", "")
        recipe["color_stats"] = suggestion.get("color_stats", {})
        recipe["color_details"] = analysis_data.get("colors", [])
    else:
        # Build from explicit colors
        if colors:
            if isinstance(colors, str):
                colors = json.loads(colors)
        else:
            colors = [[128, 128, 128]]
        recipe["colors"] = colors
        recipe["fx"] = fx if fx is not None else 9
        recipe["sx"] = sx if sx is not None else 128
        recipe["ix"] = ix if ix is not None else 200
        recipe["bri"] = bri if bri is not None else 200
        recipe["pal"] = 0
        # Build simple palette from colors
        palette = []
        n = len(colors)
        for i, c in enumerate(colors):
            pos = int(255 * i / max(n - 1, 1)) if n > 1 else 0
            palette.extend([pos, c[0], c[1], c[2]])
        if n > 1:
            palette[-4] = 255
        recipe["palette_data"] = palette

    # Determine output path
    if not output:
        # Use naming pattern from config
        naming = storage.get("naming_pattern", "{scene}_{timestamp}.json")
        safe_name = "".join(c if c.isalnum() or c in "-_" else "_" for c in name.lower().replace(" ", "_"))
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = naming.format(scene=safe_name, timestamp=timestamp)
        output = os.path.join(RECIPES_DIR, filename)

    # Ensure recipes dir exists
    os.makedirs(os.path.dirname(output) if os.path.dirname(output) else ".", exist_ok=True)

    # Write file
    with open(output, "w", encoding="utf-8") as f:
        json.dump(recipe, f, indent=2, ensure_ascii=False)

    return {
        "success": True,
        "recipe": recipe,
        "file_path": output,
        "message": f"Recipe '{name}' exported to {output}"
    }


def main():
    if "--list" in sys.argv:
        recipes = list_recipes()
        print(json.dumps({"success": True, "recipes": recipes, "count": len(recipes)}, indent=2, ensure_ascii=False))
        return

    # Parse args
    name = None
    analysis = None
    colors = None
    fx = sx = ix = bri = None
    output = None
    description = ""

    i = 1
    while i < len(sys.argv):
        arg = sys.argv[i]
        if arg == "--name" and i + 1 < len(sys.argv):
            name = sys.argv[i + 1]; i += 2
        elif arg == "--analysis" and i + 1 < len(sys.argv):
            analysis = sys.argv[i + 1]; i += 2
        elif arg == "--colors" and i + 1 < len(sys.argv):
            colors = sys.argv[i + 1]; i += 2
        elif arg == "--fx" and i + 1 < len(sys.argv):
            fx = int(sys.argv[i + 1]); i += 2
        elif arg == "--sx" and i + 1 < len(sys.argv):
            sx = int(sys.argv[i + 1]); i += 2
        elif arg == "--ix" and i + 1 < len(sys.argv):
            ix = int(sys.argv[i + 1]); i += 2
        elif arg == "--bri" and i + 1 < len(sys.argv):
            bri = int(sys.argv[i + 1]); i += 2
        elif arg == "--output" and i + 1 < len(sys.argv):
            output = sys.argv[i + 1]; i += 2
        elif arg == "--description" and i + 1 < len(sys.argv):
            description = sys.argv[i + 1]; i += 2
        else:
            i += 1

    if not name:
        print(json.dumps({"success": False, "message": "--name is required"}, ensure_ascii=False))
        sys.exit(1)

    if not analysis and not colors:
        print(json.dumps({"success": False, "message": "Either --analysis or --colors is required"}, ensure_ascii=False))
        sys.exit(1)

    result = export_recipe(name, analysis=analysis, colors=colors, fx=fx, sx=sx, ix=ix, bri=bri, output=output, description=description)
    print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
# AI: end
