#!/usr/bin/env python3
# AI: below section was generated by an AI
"""
Import and apply a light recipe from a JSON file.
Full pipeline: upload palette -> apply recipe -> save as preset.

Usage:
    python3 import_recipe.py <recipe_json_file>
    python3 import_recipe.py recipes/jasmine_blooms.json
    python3 import_recipe.py recipes/jasmine_blooms.json --save-preset "Jasmine Blooms"
    python3 import_recipe.py recipes/jasmine_blooms.json --no-palette  # skip palette upload
    python3 import_recipe.py recipes/jasmine_blooms.json --dry-run

Output: JSON with {success, steps_completed, message}
"""
import json
import os
import sys
import urllib.request

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SKILL_DIR = os.path.dirname(SCRIPT_DIR)


def get_wled_ip():
    cache_path = os.path.join(SCRIPT_DIR, ".wled_cache.json")
    if os.path.exists(cache_path):
        with open(cache_path, "r") as f:
            cache = json.load(f)
            if cache.get("ip"):
                return cache["ip"]
    config_path = os.path.join(SKILL_DIR, "config.json")
    with open(config_path, "r") as f:
        return json.load(f).get("wled", {}).get("ip", "192.168.2.66")


def wled_request(ip, path, method="GET", data=None, timeout=5):
    url = f"http://{ip}{path}"
    req = urllib.request.Request(url, headers={"User-Agent": "DoubaoWledSkill/1.0"})
    if method == "POST" and data is not None:
        req.data = json.dumps(data).encode("utf-8")
        req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            body = resp.read().decode("utf-8")
            try:
                return json.loads(body) if body else {}
            except json.JSONDecodeError:
                return {"raw": body}
    except Exception as e:
        return {"error": str(e)}


def import_recipe(recipe_file, save_preset_name=None, skip_palette=False, dry_run=False):
    """Import and apply a recipe: palette upload -> apply state -> save preset."""
    if not os.path.exists(recipe_file):
        return {"success": False, "message": f"Recipe file not found: {recipe_file}"}

    with open(recipe_file, "r", encoding="utf-8") as f:
        recipe = json.load(f)

    ip = get_wled_ip()
    steps = []

    if dry_run:
        return {
            "success": True,
            "dry_run": True,
            "recipe": recipe,
            "ip": ip,
            "message": f"Would import recipe '{recipe.get('name', 'unnamed')}' to WLED at {ip}"
        }

    # Step 1: Upload custom palette (if palette_data exists)
    palette_id = 0
    if not skip_palette and recipe.get("palette_data"):
        # Import upload function from upload_palette.py
        sys.path.insert(0, SCRIPT_DIR)
        try:
            from upload_palette import upload_palette
            pal_result = upload_palette(palette_id, recipe["palette_data"])
            steps.append({"step": "upload_palette", "result": pal_result})
            if not pal_result.get("success"):
                # Non-fatal: continue without custom palette
                steps.append({"step": "upload_palette", "warning": "Palette upload failed, continuing with built-in palette"})
        except Exception as e:
            steps.append({"step": "upload_palette", "warning": f"Palette upload skipped: {e}"})

    # Step 2: Apply recipe to WLED
    try:
        from apply_recipe import apply_recipe
        apply_result = apply_recipe(recipe)
        steps.append({"step": "apply_recipe", "result": apply_result})
        if not apply_result.get("success"):
            return {
                "success": False,
                "steps": steps,
                "message": f"Failed to apply recipe: {apply_result.get('message')}"
            }
    except Exception as e:
        return {"success": False, "steps": steps, "message": f"Apply failed: {e}"}

    # Step 3: Save as preset (optional)
    if save_preset_name:
        try:
            from save_preset import find_free_preset_id, save_preset
            pid = find_free_preset_id(ip)
            if pid:
                preset_result = save_preset(pid, save_preset_name)
                steps.append({"step": "save_preset", "result": preset_result})
            else:
                steps.append({"step": "save_preset", "warning": "No free preset ID available"})
        except Exception as e:
            steps.append({"step": "save_preset", "warning": f"Preset save failed: {e}"})

    return {
        "success": True,
        "recipe_name": recipe.get("name", "unnamed"),
        "ip": ip,
        "steps": steps,
        "colors_applied": recipe.get("colors", []),
        "fx": recipe.get("fx"),
        "sx": recipe.get("sx"),
        "ix": recipe.get("ix"),
        "bri": recipe.get("bri"),
        "message": f"Recipe '{recipe.get('name', 'unnamed')}' imported and applied to WLED at {ip}"
    }


def main():
    if len(sys.argv) < 2 or sys.argv[1].startswith("--"):
        print(json.dumps({"success": False, "message": "Usage: import_recipe.py <recipe_json_file> [--save-preset NAME] [--no-palette] [--dry-run]"}, ensure_ascii=False))
        sys.exit(1)

    recipe_file = sys.argv[1]
    save_preset_name = None
    skip_palette = False
    dry_run = False

    i = 2
    while i < len(sys.argv):
        if sys.argv[i] == "--save-preset" and i + 1 < len(sys.argv):
            save_preset_name = sys.argv[i + 1]; i += 2
        elif sys.argv[i] == "--no-palette":
            skip_palette = True; i += 1
        elif sys.argv[i] == "--dry-run":
            dry_run = True; i += 1
        else:
            i += 1

    result = import_recipe(recipe_file, save_preset_name=save_preset_name, skip_palette=skip_palette, dry_run=dry_run)
    print(json.dumps(result, indent=2, ensure_ascii=False))
    sys.exit(0 if result.get("success") else 1)


if __name__ == "__main__":
    main()
# AI: end
