#!/usr/bin/env python3
# AI: below section was generated by an AI
"""
Save current WLED state as a preset for persistent storage.
WLED 0.11+ stores presets in /presets.json on device filesystem.
Presets survive reboot and can be recalled by ID (1-250).

Usage:
    python3 save_preset.py <preset_id> "<name>"
    python3 save_preset.py 100 "Jasmine Blooms"
    python3 save_preset.py --auto "Jasmine Blooms"    # auto-find free ID
    python3 save_preset.py --list                       # list existing presets
    python3 save_preset.py --help                       # show help

Output: JSON with {success, preset_id, name, message}
"""
import json
import os
import sys
import urllib.request
import urllib.error

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
CONFIG_PATH = os.path.join(os.path.dirname(SCRIPT_DIR), "config.json")


def load_config():
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def get_wled_ip():
    """Get WLED IP from cache or config. Returns empty string if not found."""
    cache_path = os.path.join(SCRIPT_DIR, ".wled_cache.json")
    if os.path.exists(cache_path):
        try:
            with open(cache_path, "r") as f:
                cache = json.load(f)
                if cache.get("ip"):
                    return cache["ip"]
        except Exception:
            pass
    config = load_config()
    ip = config.get("wled", {}).get("ip", "")
    return ip


def wled_request(ip, path, method="GET", data=None, timeout=5):
    if not ip:
        return {"error": "WLED IP not configured. Run discover_wled.py first or set ip in config.json"}
    url = f"http://{ip}{path}"
    req = urllib.request.Request(url, headers={"User-Agent": "DoubaoWledSkill/1.0"})
    if method == "POST" and data is not None:
        req.data = json.dumps(data).encode("utf-8")
        req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            body = resp.read().decode("utf-8")
            try:
                return json.loads(body) if body else {}
            except json.JSONDecodeError:
                return {"raw": body}
    except Exception as e:
        return {"error": str(e)}


def list_presets(ip):
    """Fetch existing presets from WLED.
    Returns dict like {"0": {...}, "1": {...}} or empty dict on failure.
    """
    result = wled_request(ip, "/presets.json", method="GET")
    if isinstance(result, dict) and "error" not in result:
        return result
    # Fallback: try /edit?list=/ to list files (returns HTML, hard to parse)
    # If both fail, return empty dict so find_free_preset_id can still work
    return {}


def find_free_preset_id(ip, id_start=100, id_end=250):
    """Find a free preset ID in the configured range."""
    presets = list_presets(ip)
    used_ids = set()
    if isinstance(presets, dict):
        for k in presets.keys():
            try:
                used_ids.add(int(k))
            except (ValueError, TypeError):
                continue
    for pid in range(id_start, id_end + 1):
        if pid not in used_ids:
            return pid
    return None


def save_preset(preset_id, name):
    """Save current WLED state as a preset."""
    ip = get_wled_ip()
    if not ip:
        return {"success": False, "message": "WLED IP not configured. Run discover_wled.py first or set ip in config.json"}

    # WLED API: POST /json/state {"psave": <id>, "n": "<name>"}
    state = {"psave": preset_id}
    if name:
        state["n"] = name

    result = wled_request(ip, "/json/state", method="POST", data=state)

    # Verify by reading presets
    verify = list_presets(ip)
    saved_ok = False
    if isinstance(verify, dict):
        saved_ok = str(preset_id) in verify

    return {
        "success": "error" not in result,
        "preset_id": preset_id,
        "name": name,
        "wled_response": result,
        "verified": saved_ok,
        "message": f"Preset saved as ID {preset_id} '{name}'" if "error" not in result else f"Failed: {result.get('error')}"
    }


def main():
    if "--help" in sys.argv or "-h" in sys.argv:
        print(__doc__)
        sys.exit(0)

    config = load_config()
    storage_cfg = config.get("recipe_storage", {})
    id_start = storage_cfg.get("preset_id_start", 100)
    id_end = storage_cfg.get("preset_id_end", 250)

    if "--list" in sys.argv:
        ip = get_wled_ip()
        if not ip:
            print(json.dumps({"success": False, "message": "WLED IP not configured"}, ensure_ascii=False))
            sys.exit(1)
        presets = list_presets(ip)
        print(json.dumps({"success": True, "presets": presets, "ip": ip}, indent=2, ensure_ascii=False))
        return

    if "--auto" in sys.argv:
        name_idx = sys.argv.index("--auto") + 1
        name = sys.argv[name_idx] if name_idx < len(sys.argv) else "Unnamed Recipe"
        ip = get_wled_ip()
        if not ip:
            print(json.dumps({"success": False, "message": "WLED IP not configured. Run discover_wled.py first"}, ensure_ascii=False))
            sys.exit(1)
        pid = find_free_preset_id(ip, id_start, id_end)
        if pid is None:
            print(json.dumps({"success": False, "message": f"No free preset ID in range {id_start}-{id_end}"}, ensure_ascii=False))
            sys.exit(1)
    else:
        if len(sys.argv) < 3:
            print(json.dumps({"success": False, "message": "Usage: save_preset.py <preset_id> <name>  OR  save_preset.py --auto <name>  OR  save_preset.py --list"}, ensure_ascii=False))
            sys.exit(1)
        pid = int(sys.argv[1])
        name = sys.argv[2]
        if pid < id_start or pid > id_end:
            print(json.dumps({"success": False, "message": f"Preset ID must be in range {id_start}-{id_end}"}, ensure_ascii=False))
            sys.exit(1)

    result = save_preset(pid, name)
    print(json.dumps(result, indent=2, ensure_ascii=False))
    sys.exit(0 if result.get("success") else 1)


if __name__ == "__main__":
    main()
# AI: end
