#!/usr/bin/env python3
# AI: below section was generated by an AI
"""
Push recipe images to Android device screen via ADB.
Displays the source images so customers can see where the light recipe came from.

Features:
- Push images to Android device via ADB
- Display as a gallery slideshow using Android's Gallery app
- Supports multiple images with auto-rotation
- Falls back to opening images locally if ADB unavailable

Usage:
    python3 show_recipe_gallery.py <image1> [image2] [image3] --device 192.168.2.43:5555
    python3 show_recipe_gallery.py <image1> <image2> --device 192.168.2.43:5555 --duration 30
    python3 show_recipe_gallery.py <image1> --local  # open locally instead of ADB

Output: JSON with {success, device, images_pushed, message}
"""
import json
import os
import subprocess
import sys
import time
import tempfile
import shutil


def run_adb(args, device=None, timeout=10):
    """Run adb command and return (success, output)."""
    cmd = ["adb"]
    if device:
        cmd.extend(["-s", device])
    cmd.extend(args)
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
        return result.returncode == 0, result.stdout.strip() + result.stderr.strip()
    except subprocess.TimeoutExpired:
        return False, "timeout"
    except Exception as e:
        return False, str(e)


def check_device_online(device):
    """Check if ADB device is online and authorized."""
    success, output = run_adb(["get-state"], device=device, timeout=5)
    if success and "device" in output:
        return True, "device"
    if "unauthorized" in output:
        return False, "unauthorized"
    if "offline" in output:
        return False, "offline"
    return False, output


def connect_device(device_addr):
    """Connect to ADB device over network."""
    if ":" not in device_addr:
        device_addr = f"{device_addr}:5555"
    success, output = run_adb(["connect", device_addr], timeout=10)
    return success and "connected" in output, output


def push_and_display_images(image_paths, device, duration_sec=30):
    """Push images to device and display them as a gallery.
    Uses Android's Gallery app via ACTION_VIEW intent.
    Keeps images displayed by cycling through them with a background timer.
    """
    if not image_paths:
        return {"success": False, "message": "No images to display"}

    # Step 1: Push images to device
    pushed_files = []
    device_dir = "/sdcard/Pictures/wled_recipe"
    run_adb(["shell", "mkdir", "-p", device_dir], device=device, timeout=5)

    for i, img_path in enumerate(image_paths):
        if not os.path.exists(img_path):
            # If it's a URL, skip (should be downloaded first)
            continue
        device_path = f"{device_dir}/recipe_{i+1}.jpg"
        success, output = run_adb(["push", img_path, device_path], device=device, timeout=15)
        if success:
            pushed_files.append(device_path)
        else:
            return {"success": False, "message": f"Failed to push {img_path}: {output}"}

    if not pushed_files:
        return {"success": False, "message": "No images could be pushed"}

    # Step 2: Scan media so Gallery picks them up
    run_adb(["shell", "am", "broadcast", "-a",
             "android.intent.action.MEDIA_MOUNTED", "-d",
             f"file://{device_dir}"], device=device, timeout=5)

    # Step 3: Display images in a loop for the duration
    # Cycle through images every 5 seconds to keep screen active
    cycle_interval = 5
    cycles = max(1, duration_sec // cycle_interval)

    last_success = False
    for cycle in range(cycles):
        img_idx = cycle % len(pushed_files)
        current_image = pushed_files[img_idx]

        # Use ACTION_VIEW with file:// URI
        success, output = run_adb([
            "shell", "am", "start",
            "-a", "android.intent.action.VIEW",
            "-d", f"file://{current_image}",
            "-t", "image/*"
        ], device=device, timeout=10)

        if not success:
            # Fallback: try with content URI scheme
            success, output = run_adb([
                "shell", "am", "start",
                "-a", "android.intent.action.VIEW",
                "-d", f"content://media/external/images/media/{current_image}",
                "-t", "image/*"
            ], device=device, timeout=10)

        last_success = success
        if cycle < cycles - 1:
            time.sleep(cycle_interval)

    return {
        "success": last_success,
        "device": device,
        "images_pushed": len(pushed_files),
        "device_paths": pushed_files,
        "duration_sec": duration_sec,
        "gallery_started": last_success,
        "cycles_completed": cycles,
        "message": (f"Pushed {len(pushed_files)} images to {device} and displayed in gallery. "
                    f"Images cycled {cycles} times over {duration_sec}s while light recipe plays.")
    }


def open_images_locally(image_paths, duration_sec=30):
    """Fallback: open images locally using system default viewer."""
    if sys.platform == "darwin":
        # macOS: use open command
        for img in image_paths:
            if os.path.exists(img):
                subprocess.Popen(["open", img])
        return {
            "success": True,
            "device": "local",
            "images_pushed": len(image_paths),
            "message": f"Opened {len(image_paths)} images locally on macOS"
        }
    elif sys.platform.startswith("linux"):
        for img in image_paths:
            if os.path.exists(img):
                subprocess.Popen(["xdg-open", img])
        return {
            "success": True,
            "device": "local",
            "images_pushed": len(image_paths),
            "message": f"Opened {len(image_paths)} images locally on Linux"
        }
    else:
        return {"success": False, "message": f"Unsupported platform: {sys.platform}"}


def download_image(url, dest_dir="/tmp"):
    """Download image from URL to local file."""
    if not url.startswith(("http://", "https://")):
        return url  # Already a local file

    import urllib.request
    filename = url.split("/")[-1].split("?")[0]
    if not filename.endswith((".jpg", ".jpeg", ".png")):
        filename = f"image_{int(time.time())}.jpg"
    dest_path = os.path.join(dest_dir, filename)

    try:
        req = urllib.request.Request(url, headers={"User-Agent": "DoubaoWledSkill/1.0"})
        with urllib.request.urlopen(req, timeout=15) as resp:
            with open(dest_path, "wb") as f:
                f.write(resp.read())
        return dest_path
    except Exception as e:
        print(f"Failed to download {url}: {e}", file=sys.stderr)
        return None


def show_recipe_gallery(image_sources, device=None, duration_sec=30, local=False):
    """Main function: push images to device screen or open locally.
    image_sources: list of file paths or URLs
    device: ADB device address (e.g. "192.168.2.43:5555")
    """
    # Download any URLs first
    local_paths = []
    for src in image_sources:
        if src.startswith(("http://", "https://")):
            local_path = download_image(src)
            if local_path:
                local_paths.append(local_path)
        else:
            if os.path.exists(src):
                local_paths.append(src)

    if not local_paths:
        return {"success": False, "message": "No valid images to display"}

    # If local mode, open locally
    if local or not device:
        return open_images_locally(local_paths, duration_sec)

    # ADB mode: connect and push
    # First disconnect any stale connection
    run_adb(["disconnect", device], timeout=3)
    time.sleep(1)

    # Connect
    connected, connect_msg = connect_device(device)
    if not connected:
        # Try once more after kill-server
        run_adb(["kill-server"], timeout=5)
        time.sleep(2)
        run_adb(["start-server"], timeout=5)
        time.sleep(2)
        connected, connect_msg = connect_device(device)

    if not connected:
        # Fallback to local
        print(f"ADB connect failed ({connect_msg}), opening locally instead", file=sys.stderr)
        return open_images_locally(local_paths, duration_sec)

    # Check device state
    online, state = check_device_online(device)
    if not online:
        print(f"Device {device} is {state}, opening locally instead", file=sys.stderr)
        return open_images_locally(local_paths, duration_sec)

    # Push and display
    return push_and_display_images(local_paths, device, duration_sec)


def main():
    if "--help" in sys.argv or "-h" in sys.argv or len(sys.argv) < 2:
        print(__doc__)
        sys.exit(0)

    device = None
    duration = 30
    local = False
    images = []

    i = 1
    while i < len(sys.argv):
        arg = sys.argv[i]
        if arg == "--device" and i + 1 < len(sys.argv):
            device = sys.argv[i + 1]; i += 2
        elif arg == "--duration" and i + 1 < len(sys.argv):
            duration = int(sys.argv[i + 1]); i += 2
        elif arg == "--local":
            local = True; i += 1
        else:
            images.append(arg); i += 1

    if not images:
        print(json.dumps({"success": False, "message": "No images provided"}, ensure_ascii=False))
        sys.exit(1)

    result = show_recipe_gallery(images, device=device, duration_sec=duration, local=local)
    print(json.dumps(result, indent=2, ensure_ascii=False))
    sys.exit(0 if result.get("success") else 1)


if __name__ == "__main__":
    main()
# AI: end
