#!/usr/bin/env python3
# AI: below section was generated by an AI
"""
Upload a custom color palette to WLED device.
WLED 0.14+ supports custom palettes stored as /palette{N}.json (N=0-9).
Each palette file: {"palette": [position, R, G, B, position, R, G, B, ...]}
Positions: 0-255, RGB: 0-255

Usage:
    python3 upload_palette.py <palette_id> <palette_json_file>
    python3 upload_palette.py 0 palette.json
    python3 upload_palette.py --from-analysis <analyze_output.json>

Output: JSON with {success, palette_id, message}
"""
import json
import os
import sys
import urllib.request
import urllib.error

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
CONFIG_PATH = os.path.join(os.path.dirname(SCRIPT_DIR), "config.json")


def load_config():
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def get_wled_ip():
    """Get WLED IP from cache or config. Returns empty string if not found."""
    cache_path = os.path.join(SCRIPT_DIR, ".wled_cache.json")
    if os.path.exists(cache_path):
        try:
            with open(cache_path, "r") as f:
                cache = json.load(f)
                if cache.get("ip"):
                    return cache["ip"]
        except Exception:
            pass
    return load_config().get("wled", {}).get("ip", "")


def upload_palette_file(ip, palette_id, palette_data):
    """Upload palette as /palette{N}.json via WLED's file upload API.
    WLED uses POST /upload with multipart form data, or PUT /edit for file write.
    For newer WLED versions, we can use the /edit API with JSON.
    """
    palette_json = json.dumps({"palette": palette_data})
    filename = f"palette{palette_id}.json"

    # Method 1: Try POST /upload (multipart)
    boundary = "----DoubaoWledSkillBoundary12345"
    body = (
        f"--{boundary}\r\n"
        f'Content-Disposition: form-data; name="file"; filename="{filename}"\r\n'
        f"Content-Type: application/json\r\n\r\n"
        f"{palette_json}\r\n"
        f"--{boundary}--\r\n"
    ).encode("utf-8")

    url = f"http://{ip}/upload"
    req = urllib.request.Request(url, data=body, method="POST")
    req.add_header("Content-Type", f"multipart/form-data; boundary={boundary}")
    req.add_header("User-Agent", "DoubaoWledSkill/1.0")

    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            resp_body = resp.read().decode("utf-8")
            return {"success": True, "response": resp_body[:200], "filename": filename}
    except urllib.error.HTTPError as e:
        # Try alternative method: PUT to /edit
        return _try_put_edit(ip, filename, palette_json)
    except Exception as e:
        # Fallback to PUT /edit
        return _try_put_edit(ip, filename, palette_json)


def _try_put_edit(ip, filename, content):
    """Alternative upload method using PUT /edit (WLED 0.14+ file system API)."""
    url = f"http://{ip}/edit"
    # WLED /edit expects multipart or raw file content
    boundary = "----DoubaoWledSkillBoundary12345"
    body = (
        f"--{boundary}\r\n"
        f'Content-Disposition: form-data; name="path"\r\n\r\n'
        f"/{filename}\r\n"
        f"--{boundary}\r\n"
        f'Content-Disposition: form-data; name="file"; filename="{filename}"\r\n'
        f"Content-Type: application/json\r\n\r\n"
        f"{content}\r\n"
        f"--{boundary}--\r\n"
    ).encode("utf-8")

    req = urllib.request.Request(url, data=body, method="POST")
    req.add_header("Content-Type", f"multipart/form-data; boundary={boundary}")
    req.add_header("User-Agent", "DoubaoWledSkill/1.0")

    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            resp_body = resp.read().decode("utf-8")
            return {"success": True, "response": resp_body[:200], "filename": filename, "method": "edit"}
    except Exception as e:
        return {"success": False, "error": str(e), "filename": filename}


def upload_palette(palette_id, palette_data):
    """Upload custom palette to WLED."""
    ip = get_wled_ip()
    if not ip:
        return {"success": False, "message": "WLED IP not configured. Run discover_wled.py first or set ip in config.json"}

    # Validate palette_id range
    config = load_config()
    storage = config.get("recipe_storage", {})
    id_start = storage.get("custom_palette_id_start", 0)
    id_end = storage.get("custom_palette_id_end", 9)

    if palette_id < id_start or palette_id > id_end:
        return {"success": False, "message": f"Palette ID must be in range {id_start}-{id_end}"}

    # Validate palette_data format
    if not isinstance(palette_data, list) or len(palette_data) < 8 or len(palette_data) % 4 != 0:
        return {"success": False, "message": "Palette data must be [pos,R,G,B, pos,R,G,B, ...] with at least 2 colors"}

    # Upload
    result = upload_palette_file(ip, palette_id, palette_data)

    return {
        "success": result.get("success", False),
        "palette_id": palette_id,
        "palette_file": f"palette{palette_id}.json",
        "ip": ip,
        "upload_result": result,
        "usage_hint": f"To use this palette, set segment 'pal' to custom palette index {palette_id} (displayed as '~ Custom {palette_id} ~' after WLED reboot)",
        "note": "WLED may need a reboot to recognize the new palette. Use 'reboot' command or power cycle. NOTE: apply_recipe.py uses col array directly, so palette upload is optional.",
        "message": f"Custom palette {palette_id} uploaded to WLED at {ip}" if result.get("success") else f"Upload failed: {result.get('error', 'unknown')}"
    }


def main():
    if "--help" in sys.argv or "-h" in sys.argv:
        print(__doc__)
        sys.exit(0)

    if "--from-analysis" in sys.argv:
        # Load palette_data from analyze_image.py output
        idx = sys.argv.index("--from-analysis") + 1
        if idx >= len(sys.argv):
            print(json.dumps({"success": False, "message": "Usage: upload_palette.py --from-analysis <analyze_output.json> [palette_id]"}, ensure_ascii=False))
            sys.exit(1)
        analysis_file = sys.argv[idx]
        palette_id = int(sys.argv[idx + 1]) if idx + 1 < len(sys.argv) and not sys.argv[idx + 1].startswith("--") else 0

        with open(analysis_file, "r") as f:
            analysis = json.load(f)
        palette_data = analysis.get("palette_data")
        if not palette_data:
            print(json.dumps({"success": False, "message": "No palette_data found in analysis output"}, ensure_ascii=False))
            sys.exit(1)
    elif len(sys.argv) < 3:
        print(json.dumps({"success": False, "message": "Usage: upload_palette.py <palette_id> <palette_json_file>  OR  upload_palette.py --from-analysis <analyze_output.json> [palette_id]"}, ensure_ascii=False))
        sys.exit(1)
    else:
        palette_id = int(sys.argv[1])
        palette_file = sys.argv[2]
        with open(palette_file, "r") as f:
            palette_data = json.load(f)
        if isinstance(palette_data, dict) and "palette" in palette_data:
            palette_data = palette_data["palette"]

    result = upload_palette(palette_id, palette_data)
    print(json.dumps(result, indent=2, ensure_ascii=False))
    sys.exit(0 if result.get("success") else 1)


if __name__ == "__main__":
    main()
# AI: end
